config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'cards/index'
  get 'setting/index'
  put 'cart/quantity_update'
  #get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'registrations#index'

  resource :registration
  resource :session
  resource :dashboard
  resources :products
  resource :setting
  resources :manage_products
  resources :cart
  resource :order
  resource :payment
  resources :cards
  resources :addresses

  get 'dashboards/profile'
  get 'dashboards/addresses'
  get 'dashboards/new_address'
  get 'dashboards/edit_address'

  get 'dashboards/cards'
  get 'dashboards/new_card'
  get 'dashboards/edit_card'

  get 'dashboards/order_placed'
  get 'dashboards/order_recieved'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :payment, :dependent => :destroy
  has_many :order_item, :dependent => :destroy
  belongs_to :address
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
    @addresses = Address.where(user_id: session[:current_user_id])
  end

  def create
    # debugger
    @order = Order.create(price: 0,status: "payment_pending", user_id: session[:current_user_id], address_id: params.require(:address_id))
    # @order.save
    @cart = Cart.find_by(user_id: session[:current_user_id])

    @cart_item = CartItem.where(cart_id: @cart.id,status: "new")
    @price = 0
    @cart_item.each do |cart_item|
      product = Product.find_by(id: cart_item.product_id)
      @OrderItem = OrderItem.create(order_id: @order.id, product_id: product.id, name: product.name,description: product.description, price:  product.price.to_i * cart_item.quantity.to_i , brand: product.brand, date_first_available: product.date_first_available,quantity: cart_item.quantity)
      cart_item.update(status: "old")
      @price += @OrderItem.price.to_i

    end

    @order.update(price: @price)

    redirect_to new_payment_path(order_id: @order.id)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @addresses = Address.where(user_id: @current_user)
  end

  def create
    order = Order.create(price: 0,status: "payment_pending", user_id: @current_user, address_id: params.require(:address_id))
    cart = Cart.find_by(user_id: @current_user)

    cart_items = CartItem.where(cart_id: cart.id).new_order
    price = 0
    cart_items.each do |cart_item|
      product = Product.find_by(id: cart_item.product_id)
      order_item = OrderItem.create(order_id: order.id, product_id: product.id, name: product.name,description: product.description, price:  product.price.to_i * cart_item.quantity.to_i , brand: product.brand, date_first_available: product.date_first_available,quantity: cart_item.quantity)
      cart_item.update(status: "old")
      price += order_item.price.to_i
    end
    order.update_attribute(:price, price)
    redirect_to new_payment_path(order_id: order.id)
  end

end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%# render "layouts/home_logout" %>

<div class="container-fluid">

  <div class="row">

    <div class="col-xl-2">

      <%= render partial: "layouts/side_navbar", locals: {selected: "cart"} %>
    </div>

    <div class="col-xl-9" style="width: 1000px; height: 500px; background-color:#4B515D">
      <h1>Select Address</h1>
      <div class="row py-xl-3">
        <% @addresses.each do |address| %>

          <div class="col-xl-3 py-md-1 mx-md-3 border border-dark" style="background-color:#ffffff; width: 300px; height: 200px;" align="center">
            <br>
            Name:           <%= address.name %> <br>
            Contact Number: <%= address.contact_number %><br>
            Address:        <%= address.address %><br>
            landmark:       <%= address.landmark %> <br>
            <%= button_to "Place Order",order_index_path(address_id: address.id) , method: "post",data: { confirm: 'Place order ?' } %>
          </div>
        <% end %>
        <div class="col-xl-3 py-md-3 mx-md-3 border border-dark text-center" style="background-color:#ffffff; width: 300px; height: 100px;">
          <%= link_to address_path(id: current_user.id) do %>
            <%= image_tag("add_icon.png",size: "60") %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>