config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'cards/index'
  get 'setting/index'
  put 'cart/quantity_update'
  #get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'registrations#index'

  resource :registration
  resource :session
  resource :dashboard
  resources :products
  resource :setting
  resources :manage_products
  resources :cart
  resource :order
  resource :payment
  resources :cards
  resources :addresses

  get 'dashboards/profile'
  get 'dashboards/addresses'
  get 'dashboards/new_address'
  get 'dashboards/edit_address'

  get 'dashboards/cards'
  get 'dashboards/new_card'
  get 'dashboards/edit_card'

  get 'dashboards/order_placed'
  get 'dashboards/order_recieved'

end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, presence: true,length: { in: 3..20 }
  validates :contact_number, presence: true, length: { is: 10 }, numericality: { only_integer: true , greater_than: 0}
  validates :address, presence: true
  validates :landmark, presence: true


  validate :address_associated

  def address_associated
    if Order.find_by(address_id: self.id)
      false
    else
      true
    end
  end

  belongs_to :user
  has_many :order, :dependent => :nullify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :card_holder_name, presence: true
  validates :cvv, presence: true, length: { is: 3 }
  validates :expiry, presence: true
  validates :card_number, presence: true, length: { is: 12 }, numericality: { only_integer: true , greater_than: 0}


  validate :expiry_cannot_be_in_the_past

  def expiry_cannot_be_in_the_past
    if expiry.present? && expiry < Date.today
      errors.add(:expiry, "Your card has expired")
    end
  end

  has_many :payment, :dependent => :nullify
  belongs_to :user, optional: true

end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user, optional: true
  has_many :cart_item, :dependent => :destroy

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  def add
    self.update_attribute(:quantity, quantity + 1)
  end

  def sub
    if quantity > 1
      self.update_attribute(:quantity, quantity - 1)
    end
  end

  scope :new_order, -> {where(status: "new")}

  belongs_to :cart
  belongs_to :product

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :payment, :dependent => :destroy
  has_many :order_item, :dependent => :destroy
  belongs_to :address
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  belongs_to :card, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true , greater_than: 0}
  validates :user_id, presence: true
  validates :brand, presence: true
  validates :date_first_available, presence: true
  validate :date_first_available_cannot_be_in_the_future

  def date_first_available_cannot_be_in_the_future
    if date_first_available.present? && date_first_available > Date.today
      errors.add(:date_first_available, "can't be in the future")
    end
  end

  belongs_to :user
  has_many :cart_item, :dependent => :destroy
  has_one_attached :product_picture
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, uniqueness: true, presence: true,length: { in: 3..20 }
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true,length: { minimum: 2 }
  validates :phone_number, presence: true,length: { is: 10 }, numericality: { only_integer: true , greater_than: 0}
  validates :alternate_number, presence: true,length: { is: 10 }, numericality: { only_integer: true , greater_than: 0}


  def self.authenticate(params)
    if @user = User.where(user_name: params[:user_name]).first
      if @user.password == params[:password]
        @user
      end
    end
  end

  has_one :cart, :dependent => :destroy
  has_many :order, :dependent => :destroy
  has_many :product, :dependent => :destroy
  has_many :address, :dependent => :destroy
  has_many :feedback, :dependent => :destroy
  has_many :card, :dependent => :destroy
  has_one_attached :picture

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @payment_id = params[:id]
    @card = Card.new
  end

  def index
    @payment_id = params[:id]
    payment = Payment.find_by(id: @payment_id)
    payment.update_attributes(mode: params[:mode],status: params[:status])
    @cards = Card.where(user_id: @current_user)
  end

  def create
    @card = Card.new(card_parameter)
    if params[:type] == "order"
      if @card.save
        @payment_id = params[:id]
        if @card.save
          redirect_to cards_path(id: @payment_id,mode: "card_payment",status: "pending")
        else
          flash[:danger] = "You have not entered a valid card"
          render :new
        end
      else
        flash[:danger] = "Card not added"
        redirect_to dashboard_path(selected: "card")
      end
    elsif params[:type] == "dashboard"
      if @card.save
        flash[:success] = "Card added successsfully"
        redirect_to dashboard_path(selected: "card")
      else
        flash[:danger] = "Card not added"
        redirect_to dashboard_path(selected: "card")
      end
    end
  end

  def destroy
    card = Card.find(params[:id])
    if card.destroy
      flash[:success] = "card deleted successfully"
      redirect_to dashboard_path(selected: "card")
    else
      flash[:danger] = "deletion failed"
    end
  end

  def update
    card = Card.find(params[:id])
    card.update(card_parameter)
    redirect_to dashboard_path(selected: "card")
  end

  private

  def card_parameter
    params.require(:card).permit(:card_number,:expiry,:cvv,:card_holder_name,:user_id)
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def update
    if(CartItem.find_by(product_id: params[:product_id],status: params[:status],
      cart_id: params[:id]))
      @exists = true
    else
      cart = CartItem.create(product_id: params[:product_id],cart_id: params[:id],
        status: params[:status],quantity: params[:quantity])
        @exists = false
      end
    end

    def index
      @cart = Cart.find_by(user_id: @current_user)
      @cart_items = CartItem.where(cart_id: @cart.id).new_order
      @products= Array.new
      @cart_items.each do |product|
        @products << Product.find_by(id: product.product_id)
      end
    end

    def destroy
      cart = CartItem.new_order.find_by(cart_id: params[:id])
      cart.update_attribute(:status ,"old")
      redirect_to cart_index_path
    end

    def quantity_update
      @cart = Cart.find_by(user_id: @current_user)
      @cart_item = CartItem.new_order.find_by(cart_id: @cart.id, product_id: params[:product])
      if params[:type] == "add"
        @cart_item.add
      elsif params[:type] == "subtract"
        @cart_item.sub
      end
    end

  end

app/controllers/manage_products_controller.rb
class ManageProductsController < ApplicationController

  def index
    @products = Product.where(user_id: @current_user)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(parameter_for)
    unless @product.save
      render :new
    else
      flash[:success] = "Successfully Added"
      redirect_to manage_products_path
    end
  end

  def edit
    @product = Product.find_by(id: params[:id])
  end

  def update
    @product = Product.find_by(id: params[:id])
    unless @product.update(product_parameter)
      render :edit
    else
      flash[:success] = "Successfully Edited"
      redirect_to manage_products_path
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.product_picture.purge
  end

  private

  def product_parameter
    params.require(:product).permit(:name,:description,:price,:brand,:date_first_available,:product_picture,:user_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find_by(id: session[:current_user_id])
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/views/manage_products/_picture.html.erb
<%#  @user.picture  %>
<% image_present = product_pic.product_picture.blob.present? rescue nil %>
<% if( image_present ) %>
  <%= image_tag(product_pic.product_picture, size: "200") %>
<% else %>
  <%=  image_tag(:no_product, size: "200") %>
<% end %>

app/views/manage_products/destroy.js.erb
$(".has_picture").html("<%= j render partial: 'picture', locals: {product_pic: @product} %>")

app/views/manage_products/edit.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%# render "layouts/home_logout" %>

<div class="container-fluid">

  <div class="row">

    <div class="col-xl-2" style="background-color:#ffffff">

      <%= render partial: "layouts/side_navbar", locals: {selected: "manage_products"} %>
    </div>

    <div class="col-xl-9" style="width: 1000px; background-color:#4B515D">

      <div class="px-xl-5 py-xl-5">
        <%= form_for @product, url: manage_product_path(id: @product.id), method: "put", html: {class: "form-horizontal center text-light"}, remote: true do |f| %>

        <div class="row">

          <div class="col-xl-6">

            <div class="row pl-xl-3 has_picture">
              <%= render partial: "picture", locals: {product_pic: @product}%>
            </div>

            <!-- <div class="row testClass">
              <%# render partial: "hello", locals: {word: "hello"} %>
            </div> -->

            <div class="py-xl-3">
              <%= link_to 'Delete', manage_product_path(id: @product.id), class: 'btn btn-default btn-primary', method: 'delete', remote: true %>
              <%= f.file_field :product_picture,class: "btn btn-default btn-primary" %>
            </div>
          </div>
        </div>

        <div class="row">

          <div class="col-xl-6">

            <div class="row pl-xl-3">
              <%= f.label "Name:",class: " control-label" %>
            </div>
            <%= f.text_field :name,value: @product.name, class: "form-control" %>

            <% if @product.errors[:name].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @product.errors[:name].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>

          <div class="col-xl-6">

            <div class="row pl-xl-3">
              <%= f.label "Description:", class: " control-label" %>
            </div>
            <%= f.text_field :description, value: @product.description,class: "form-control" %>

            <% if @product.errors[:description].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @product.errors[:description].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>
        </div>

        <div class="row">

          <div class="col-xl-6">

            <div class="row pl-xl-3 py-xl-2">
              <%= f.label "Price:", class: " control-label" %>
            </div>
            <%= f.text_field :price,value: @product.price , class: "form-control" %>

            <% if @product.errors[:price].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @product.errors[:price].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>

          <div class="col-xl-6">

            <div class="row pl-xl-3 py-xl-2">
              <%= f.label "Brand:", class: " control-label" %>
            </div>
            <%= f.text_field :brand,value: @product.brand, class: "form-control" %>

            <% if @product.errors[:brand].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @product.errors[:brand].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>

        </div>

        <div class="row pl-xl-3 py-xl-2">
          <%= f.label  "Date First Availabe:", class: " control-label" %>
        </div>

        <div class="row">

          <div class="col-xl-6">
            <%= f.date_field :date_first_available,value: @product.date_first_available, class: "form-control" %>

            <% if @product.errors[:date_first_available].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @product.errors[:date_first_available].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>
        </div>

        <div class="row pt-xl-5 pl-xl-3">
          <%= f.submit "Submit", class: "btn btn-default btn-primary", data: { confirm: 'Are you sure ?' }  %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/manage_products/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%# render "layouts/home_logout" %>

<div class="container-fluid">

  <div class="row">

    <div class="col-xl-2">

      <%= render partial: "layouts/side_navbar", locals: {selected: "manage_products"} %>
    </div>

    <div class="col-xl-9" style="width: 1000px; height: 500px; background-color:#4B515D">
      <div class="row py-xl-3">
        <% @products.each do |product| %>

          <div class="col-xl-3 py-md-1 mx-md-3 border border-dark" style="background-color:#ffffff; width: 300px; height: 300px;" align="center">
            <%= link_to edit_manage_product_path(id: product.id) do  %>
              <br>
              <%# product.id %>
              <%= render partial: "picture", locals: {product_pic: product}%><br>
              Name:        <%= product.name %> <br>
              Description: <%= product.description %><br>
              Price:       <%= product.price %><br>
            </div>
          <% end %>
        <% end %>
        <div class="col-xl-3 py-md-3 mx-md-3 border border-dark text-center" style="background-color:#ffffff; width: 300px; height: 300px;">
          <br><br><br><br><br>
          <%= link_to new_manage_product_path do%>
          <%= image_tag("add_icon.png",size: "60") %>
          <%end%>
          <br>

          <br><br><br>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/manage_products/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<%# render "layouts/home_logout" %>

<div class="container-fluid">

  <div class="row">

    <div class="col-xl-2" style="background-color:#ffffff">

      <%= render partial: "layouts/side_navbar", locals: {selected: "manage_products"} %>
    </div>

    <div class="col-xl-9" style="width: 1000px; background-color:#4B515D">

      <div class="px-xl-5 py-xl-5">
        <%= form_for @product, url: manage_products_path, method: "post", html: {class: "form-horizontal center text-light"} do |f| %>

        <div class="row">

          <div class="col-xl-6">

          <div class="py-xl-3">
            <%= f.file_field :product_picture,class: "btn btn-default btn-primary" %>
            <%= f.hidden_field :user_id,value: current_user.id %>
          </div>
        </div>
      </div>

      <div class="row">

        <div class="col-xl-6">

          <div class="row pl-xl-3">
            <%= f.label "Name:", class: " control-label" %>
          </div>
          <%= f.text_field :name, class: "form-control" %>

          <% if @product.errors[:name].any?%>
          <div class="row pl-xl-3 text-left">
            <div class="text-danger">
              <% @product.errors[:name].each do |error| %>
                **<%= error %> <br>
              <% end %>
            </div>
          </div>
          <% end %>

        </div>

        <div class="col-xl-6">

          <div class="row pl-xl-3">
            <%= f.label "Description:", class: " control-label" %>
          </div>
          <%= f.text_area :description, class: "form-control" %>

          <% if @product.errors[:description].any?%>
          <div class="row pl-xl-3 text-left">
            <div class="text-danger">
              <% @product.errors[:description].each do |error| %>
                **<%= error %> <br>
              <% end %>
            </div>
          </div>
          <% end %>

        </div>
      </div>

      <div class="row">

        <div class="col-xl-6">

          <div class="row pl-xl-3 py-xl-2">
            <%= f.label "Price:", class: " control-label" %>
          </div>
          <%= f.text_field :price, class: "form-control" %>


            <% if @product.errors[:price].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @product.errors[:price].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

        </div>

        <div class="col-xl-6">

          <div class="row pl-xl-3 py-xl-2">
            <%= f.label "Brand:", class: " control-label" %>
          </div>
          <%= f.text_field :brand, class: "form-control" %>

          <% if @product.errors[:brand].any?%>
          <div class="row pl-xl-3 text-left">
            <div class="text-danger">
              <% @product.errors[:brand].each do |error| %>
                **<%= error %> <br>
              <% end %>
            </div>
          </div>
          <% end %>

        </div>

      </div>

      <div class="row pl-xl-3 py-xl-2">
        <%= f.label  "Date First Availabe:", class: " control-label" %>
      </div>

      <div class="row">

        <div class="col-xl-6">
          <%= f.date_field :date_first_available, class: "form-control" %>

          <% if @product.errors[:date_first_available].any?%>
          <div class="row pl-xl-3 text-left">
            <div class="text-danger">
              <% @product.errors[:date_first_available].each do |error| %>
                **<%= error %> <br>
              <% end %>
            </div>
          </div>
          <% end %>

        </div>
      </div>

      <div class="row pt-xl-5 pl-xl-3">
        <%= f.submit "Submit", class: "btn btn-default btn-primary", data: { confirm: 'Are you sure ?' }  %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/manage_products/update.js.erb
$(".has_picture").html("<%= j render partial: 'picture', locals: {product_pic: @product} %>")