config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'cards/index'
  get 'setting/index'
  put 'cart/quantity_update'
  #get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'registrations#index'

  resource :registration
  resource :session
  resource :dashboard
  resources :products
  resource :setting
  resources :manage_products
  resources :cart
  resource :order
  resource :payment
  resources :cards
  resources :addresses

  get 'dashboards/profile'
  get 'dashboards/addresses'
  get 'dashboards/new_address'
  get 'dashboards/edit_address'

  get 'dashboards/cards'
  get 'dashboards/new_card'
  get 'dashboards/edit_card'

  get 'dashboards/order_placed'
  get 'dashboards/order_recieved'

end

app/models/address.rb
class Address < ApplicationRecord
  validates :name, presence: true,length: { in: 3..20 }
  validates :contact_number, presence: true, length: { is: 10 }, numericality: { only_integer: true , greater_than: 0}
  validates :address, presence: true
  validates :landmark, presence: true


  validate :address_associated

  def address_associated
    if Order.find_by(address_id: self.id)
      false
    else
      true
    end
  end

  belongs_to :user
  has_many :order, :dependent => :nullify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :card_holder_name, presence: true
  validates :cvv, presence: true, length: { is: 3 }
  validates :expiry, presence: true
  validates :card_number, presence: true, length: { is: 12 }, numericality: { only_integer: true , greater_than: 0}


  validate :expiry_cannot_be_in_the_past

  def expiry_cannot_be_in_the_past
    if expiry.present? && expiry < Date.today
      errors.add(:expiry, "Your card has expired")
    end
  end

  has_many :payment, :dependent => :nullify
  belongs_to :user, optional: true

end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user, optional: true
  has_many :cart_item, :dependent => :destroy

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  def add
    self.update_attribute(:quantity, quantity + 1)
  end

  def sub
    if quantity > 1
      self.update_attribute(:quantity, quantity - 1)
    end
  end

  scope :new_order, -> {where(status: "new")}

  belongs_to :cart
  belongs_to :product

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :payment, :dependent => :destroy
  has_many :order_item, :dependent => :destroy
  belongs_to :address
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  belongs_to :card, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true , greater_than: 0}
  validates :user_id, presence: true
  validates :brand, presence: true
  validates :date_first_available, presence: true
  validate :date_first_available_cannot_be_in_the_future

  def date_first_available_cannot_be_in_the_future
    if date_first_available.present? && date_first_available > Date.today
      errors.add(:date_first_available, "can't be in the future")
    end
  end

  belongs_to :user
  has_many :cart_item, :dependent => :destroy
  has_one_attached :product_picture
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, uniqueness: true, presence: true,length: { in: 3..20 }
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true,length: { minimum: 2 }
  validates :phone_number, presence: true,length: { is: 10 }, numericality: { only_integer: true , greater_than: 0}
  validates :alternate_number, presence: true,length: { is: 10 }, numericality: { only_integer: true , greater_than: 0}


  def self.authenticate(params)
    if @user = User.where(user_name: params[:user_name]).first
      if @user.password == params[:password]
        @user
      end
    end
  end

  has_one :cart, :dependent => :destroy
  has_many :order, :dependent => :destroy
  has_many :product, :dependent => :destroy
  has_many :address, :dependent => :destroy
  has_many :feedback, :dependent => :destroy
  has_many :card, :dependent => :destroy
  has_one_attached :picture

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @payment_id = params[:id]
    @card = Card.new
  end

  def index
    @payment_id = params[:id]
    payment = Payment.find_by(id: @payment_id)
    payment.update_attributes(mode: params[:mode],status: params[:status])
    @cards = Card.where(user_id: @current_user)
  end

  def create
    @card = Card.new(card_parameter)
    if params[:type] == "order"
      if @card.save
        @payment_id = params[:id]
        if @card.save
          redirect_to cards_path(id: @payment_id,mode: "card_payment",status: "pending")
        else
          flash[:danger] = "You have not entered a valid card"
          render :new
        end
      else
        flash[:danger] = "Card not added"
        redirect_to dashboard_path(selected: "card")
      end
    elsif params[:type] == "dashboard"
      if @card.save
        flash[:success] = "Card added successsfully"
        redirect_to dashboard_path(selected: "card")
      else
        flash[:danger] = "Card not added"
        redirect_to dashboard_path(selected: "card")
      end
    end
  end

  def destroy
    card = Card.find(params[:id])
    if card.destroy
      flash[:success] = "card deleted successfully"
      redirect_to dashboard_path(selected: "card")
    else
      flash[:danger] = "deletion failed"
    end
  end

  def update
    card = Card.find(params[:id])
    card.update(card_parameter)
    redirect_to dashboard_path(selected: "card")
  end

  private

  def card_parameter
    params.require(:card).permit(:card_number,:expiry,:cvv,:card_holder_name,:user_id)
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def update
    if(CartItem.find_by(product_id: params[:product_id],status: params[:status],
      cart_id: params[:id]))
      @exists = true
    else
      cart = CartItem.create(product_id: params[:product_id],cart_id: params[:id],
        status: params[:status],quantity: params[:quantity])
        @exists = false
      end
    end

    def index
      @cart = Cart.find_by(user_id: @current_user)
      @cart_items = CartItem.where(cart_id: @cart.id).new_order
      @products= Array.new
      @cart_items.each do |product|
        @products << Product.find_by(id: product.product_id)
      end
    end

    def destroy
      cart = CartItem.new_order.find_by(cart_id: params[:id])
      cart.update_attribute(:status ,"old")
      redirect_to cart_index_path
    end

    def quantity_update
      @cart = Cart.find_by(user_id: @current_user)
      @cart_item = CartItem.new_order.find_by(cart_id: @cart.id, product_id: params[:product])
      if params[:type] == "add"
        @cart_item.add
      elsif params[:type] == "subtract"
        @cart_item.sub
      end
    end

  end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    unless Cart.find_by(user_id: @current_user)
      Cart.create(user_id: @current_user)
    end

    @user = User.find_by(id: @current_user)
    @addresses = Address.where(user_id: @current_user)
    @cards = Card.where(user_id: @current_user)
    @selected = params[:selected]
  end

  def profile
    @user = User.find_by(id: @current_user)
  end

  def addresses
    @addresses = Address.where(user_id: @current_user)
  end

  def edit_address
      @address = Address.find(params[:id])
  end

  def cards
    user = User.find_by(id: @current_user)
    @cards = Card.where(user_id: @current_user)
  end

  def edit_card
    @card = Card.find(params[:id])
  end

  def order_placed
    @user = User.find_by(id: @current_user)
    @orders = Order.where(user_id: @user.id)
  end

  def order_recieved
    @user = User.find_by(id: @current_user)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find_by(id: session[:current_user_id])
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/views/dashboards/_addresses.html.erb
<table class="table table-hover table-light">
  <!-- <thead> -->
  <tbody>
      <% addresses.each do |address| %>
      <tr>
        <td>
          <div class="row">
            <div class="col-xl-4">
              Name :<%= address.name%>
            </div>
            <div class="col-xl-6">
              Contact Number :  <%= address.contact_number%>
            </div>
            <div class="col-xl-1">
              <%= link_to "delete", address_path(id: address.id), method: "delete",class: "btn"%>
            </div>
            <div class="col-xl-1">
              <%= link_to "edit", dashboards_edit_address_path(id: address.id) , class: "btn" , remote: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-xl-4">
              Address : <%= address.address%>
            </div>
          </div>
          <div class="row">
            <div class="col-xl-4">
              Landmark:<%= address.landmark%>
            </div>
          </div>
        </td>
      </tr>
      <% end %>
    <tr>
      <td>
        <%= link_to "add new address",dashboards_new_address_path, remote: true %>
      </td>
    </tr>
  </tbody>
  <!-- </thead> -->
  <!-- <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    </tbody> -->
</table>

app/views/dashboards/_cards.html.erb
<table class="table table-hover table-light">
  <!-- <thead> -->
  <tbody>
      <% card.each do |card| %>
      <tr>
        <td>
          <div class="row">
            <div class="col-xl-4">
              Card Number :<%= card.card_number%>
            </div>
            <div class="col-xl-6">
              Expiry :  <%= card.expiry%>
            </div>
            <div class="col-xl-1">
              <%= link_to "delete", card_path(id: card.id), method: "delete",class: "btn"%>
            </div>
            <div class="col-xl-1">
              <%= link_to "edit", dashboards_edit_card_path(id: card.id) , class: "btn" , remote: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-xl-4">
              CVV : <%= card.cvv%>
            </div>
          </div>
          <div class="row">
            <div class="col-xl-4">
              Card Holer Name : <%= card.card_holder_name%>
            </div>
          </div>
        </td>
      </tr>
      <% end %>
    <tr>
      <td>
        <%= link_to "add new card",dashboards_new_card_path, remote: true %>
      </td>
    </tr>
  </tbody>
  <!-- </thead> -->
  <!-- <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    </tbody> -->
</table>

app/views/dashboards/_edit_address.html.erb
<br><br><br>
<br><br><br>
<%= form_for :address, url: address_path(id: address.id), method: "put", html: {class: "form-horizontal center text-light"} do |f| %>

<div class="row">

  <div class="col-xl-6">

    <div class="row pl-xl-3">
      <%= f.label "Name:",class: " control-label" %>
    </div>
    <%= f.text_field :name, value: address.name,class: "form-control" %>
  </div>

  <div class="col-xl-6">

    <div class="row pl-xl-3">
      <%= f.label "Contact Number:", class: " control-label" %>
    </div>
    <%= f.text_field :contact_number,value: address.contact_number,class: "form-control" %>
  </div>
</div>

<div class="row">

  <div class="col-xl-6">

    <div class="row pl-xl-3 py-xl-2">
      <%= f.label "Address:", class: " control-label" %>
    </div>
    <%= f.text_field :address, value: address.address,class: "form-control" %>
  </div>

  <div class="col-xl-6">

    <div class="row pl-xl-3 py-xl-2">
      <%= f.label "Landmark:", class: " control-label" %>
    </div>
    <%= f.text_area :landmark, value: address.landmark, class: "form-control" %>
  </div>

</div>


<div class="row pt-xl-5 pl-xl-3">
  <%= f.submit "Add Address", class: "btn btn-default btn-primary" %>
</div>
<% end %>

app/views/dashboards/_edit_card.html.erb
<br><br><br>
<%= form_for :card, url: card_path(id: card.id), method: "put", html: {class: "form-horizontal center text-light"} do |f| %>

<div class="row">

  <div class="col-xl-6">

    <div class="row pl-xl-3">
      <%= f.label "Card Number:",class: " control-label" %>
    </div>
    <%= f.text_field :card_number, value: card.card_number,class: "form-control" %>
  </div>

  <div class="col-xl-6">

    <div class="row pl-xl-3">
      <%= f.label "Expiry:", class: " control-label" %>
    </div>
    <%= f.date_field :expiry,value: card.expiry,class: "form-control" %>
    <%= f.hidden_field :user_id,value: current_user.id,class: "form-control" %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </div>
</div>

<div class="row">

  <div class="col-xl-6">

    <div class="row pl-xl-3 py-xl-2">
      <%= f.label "CVV:", class: " control-label" %>
    </div>
    <%= f.text_field :cvv, value: card.cvv,class: "form-control" %>
  </div>

  <div class="col-xl-6">

    <div class="row pl-xl-3 py-xl-2">
      <%= f.label "Crd Holder Name :", class: " control-label" %>
    </div>
    <%= f.text_area :card_holder_name, value: card.card_holder_name, class: "form-control" %>
  </div>

</div>


<div class="row pt-xl-5 pl-xl-3">
  <%= f.submit "Add Card", class: "btn btn-default btn-primary" %>
</div>
<% end %>

app/views/dashboards/_new_address.html.erb
<br><br><br>
<%= form_for :address, url: addresses_path(type: "dashboard"), method: "post", html: {class: "form-horizontal center text-light"} do |f| %>

<div class="row">

  <div class="col-xl-6">

    <div class="row pl-xl-3">
      <%= f.label "Name:",class: " control-label" %>
    </div>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="col-xl-6">

    <div class="row pl-xl-3">
      <%= f.label "Contact Number:", class: " control-label" %>
    </div>
    <%= f.text_field :contact_number,class: "form-control" %>
  </div>
</div>

<div class="row">

  <div class="col-xl-6">

    <div class="row pl-xl-3 py-xl-2">
      <%= f.label "Address:", class: " control-label" %>
    </div>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="col-xl-6">

    <div class="row pl-xl-3 py-xl-2">
      <%= f.label "Landmark:", class: " control-label" %>
    </div>
    <%= f.text_area :landmark, class: "form-control" %>
  </div>

</div>


<div class="row pt-xl-5 pl-xl-3">
  <%= f.submit "Add Address", class: "btn btn-default btn-primary" %>
</div>
<% end %>

app/views/dashboards/_order_placed.html.erb
<table class="table table-hover table-light">
  <!-- <thead> -->
  <tbody>
    <% orders.each do |order| %>
    <tr>
      <td>
        <div class="row">
          <h3> Order Id : <%= order.id %></h3>
          </div>
          <table class="table table-hover table-light">
            <tbody>
              <% OrderItem.where(order_id: order.id).each do |order_item| %>
              <!-- <thead> -->
              <tr>
                <td>

                  Name : <%= order_item.name %>
                  Description : <%= order_item.description %>
                  Price : <%= order_item.price %>
                  Brand : <%= order_item.brand %>
                  Date Fist Available : <%= order_item.date_first_available %>
                  Quantity : <%= order_item.quantity %>

                  <% end %>

                </tr>
              </td>
            </tbody>
          </table>
          <div class="row">
            <div class="col-xl-6">
              <h6>Status: <%= order.status%></h6>
            </div>
            <div class="col-xl-6">
              <h6>Price: <%= order.price%></h6>
            </div>
          </div>
          </td>
        </tr>
        <% end %>
      </tbody>
      <!-- </thead> -->
      <!-- <tbody>
      <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
  </table>
  </tbody> -->

app/views/dashboards/_order_recieved.html.erb
<div class="px-xl-5 py-xl-5">
  <%= form_for :user do |f| %>

  <div class="row">

    <div class="col-xl-6">

      <div class="row pl-xl-3">
        <%= f.label "Email:",class: " control-label" %>
      </div>
        <%= f.label :email,value: user.email, class: "form-control" %>
    </div>

    <div class="col-xl-6">

      <div class="row pl-xl-3">
        <%= f.label "Password:", class: " control-label" %>
      </div>
        <%= f.label :password, value: user.password,class: "form-control" %>
    </div>
  </div>

  <div class="row">

    <div class="col-xl-6">

      <div class="row pl-xl-3 py-xl-2">
        <%= f.label :user_name, "User Name:", class: " control-label" %>
      </div>
        <%= f.label :user_name,value: user.user_name, class: "form-control" %>
    </div>

    <div class="col-xl-6">

      <div class="row pl-xl-3 py-xl-2">
        <%= f.label "Phone Number:", class: " control-label" %>
      </div>
        <%= f.label :phone_number,value: user.phone_number, class: "form-control" %>
    </div>

  </div>

  <div class="row pl-xl-3 py-xl-2">
      <%= f.label  "Alternate Number:", class: " control-label" %>
  </div>

  <div class="row">
    <div class="col-xl-6">
      <%= f.label :alternate_number,value: user.alternate_number, class: "form-control" %>
    </div>
  </div>

  <% end %>

</div>

app/views/dashboards/addresses.js.erb
$(".dashboards").html("<%= j render partial: "addresses", locals: {addresses: @addresses} %>")

app/views/dashboards/cards.js.erb
$(".dashboards").html("<%= j render partial: "cards", locals: {card: @cards} %>")

app/views/dashboards/edit_address.js.erb
$(".dashboards").html("<%= j render partial: "edit_address",locals: {address: @address} %>")

app/views/dashboards/new_address.js.erb
$(".dashboards").html("<%= j render partial: "new_address" %>")

app/views/dashboards/new_card.js.erb
$(".dashboards").html("<%= j render partial: "new_card" %>")

app/views/dashboards/order_placed.js.erb
$(".dashboards").html("<%= j render partial: "order_placed", locals: {orders: @orders} %>")

app/views/dashboards/order_recieved.js.erb
$(".dashboards").html("<%= j render partial: "order_recieved", locals: {user: @user} %>")