config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'cards/index'
  get 'setting/index'
  put 'cart/quantity_update'
  #get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'registrations#index'

  resource :registration
  resource :session
  resource :dashboard
  resources :products
  resource :setting
  resources :manage_products
  resources :cart
  resource :order
  resource :payment
  resources :cards
  resources :addresses

  get 'dashboards/profile'
  get 'dashboards/addresses'
  get 'dashboards/new_address'
  get 'dashboards/edit_address'

  get 'dashboards/cards'
  get 'dashboards/new_card'
  get 'dashboards/edit_card'

  get 'dashboards/order_placed'
  get 'dashboards/order_recieved'

end

app/models/card.rb
class Card < ApplicationRecord
  validates :card_holder_name, presence: true
  validates :cvv, presence: true, length: { is: 3 }
  validates :expiry, presence: true
  validates :card_number, presence: true, length: { is: 12 }, numericality: { only_integer: true , greater_than: 0}


  validate :expiry_cannot_be_in_the_past

  def expiry_cannot_be_in_the_past
    if expiry.present? && expiry < Date.today
      errors.add(:expiry, "Your card has expired")
    end
  end

  has_many :payment, :dependent => :nullify
  belongs_to :user, optional: true

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    @payment_id = params[:id]
    @card = Card.new
  end

  def index
    @payment_id = params[:id]
    payment = Payment.find_by(id: @payment_id)
    payment.update_attributes(mode: params[:mode],status: params[:status])
    @cards = Card.where(user_id: @current_user)
  end

  def create
    @card = Card.new(card_parameter)
    if params[:type] == "order"
      if @card.save
        @payment_id = params[:id]
        if @card.save
          redirect_to cards_path(id: @payment_id,mode: "card_payment",status: "pending")
        else
          flash[:danger] = "You have not entered a valid card"
          render :new
        end
      else
        flash[:danger] = "Card not added"
        redirect_to dashboard_path(selected: "card")
      end
    elsif params[:type] == "dashboard"
      if @card.save
        flash[:success] = "Card added successsfully"
        redirect_to dashboard_path(selected: "card")
      else
        flash[:danger] = "Card not added"
        redirect_to dashboard_path(selected: "card")
      end
    end
  end

  def destroy
    card = Card.find(params[:id])
    if card.destroy
      flash[:success] = "card deleted successfully"
      redirect_to dashboard_path(selected: "card")
    else
      flash[:danger] = "deletion failed"
    end
  end

  def update
    card = Card.find(params[:id])
    card.update(card_parameter)
    redirect_to dashboard_path(selected: "card")
  end

  private

  def card_parameter
    params.require(:card).permit(:card_number,:expiry,:cvv,:card_holder_name,:user_id)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="container-fluid">

  <div class="row">

    <div class="col-xl-2">

      <%= render partial: "layouts/side_navbar", locals: {selected: "cart"} %>
    </div>

    <div class="col-xl-9" style="width: 1000px; background-color:#4B515D">
      <div class="row py-xl-3">
        <% @cards.each do |card| %>

        <div class="col-xl-3 py-md-1 mx-md-3 border border-dark" style="background-color:#ffffff; width: 300px; height: 200px;" align="center">
          <br>
          Card Number:     <%= card.card_number %> <br>
          cvv:             <%= card.cvv %><br>
          Expiry Date:     <%= card.expiry %><br>
          card_holder_name:<%= card.card_holder_name %> <br>

          <%= button_to "Place Order with this card",payment_path(id: card.id,payment_id: @payment_id) , method: "put",data: { confirm: 'Place order ?' } %>
        </div>
        <% end %>
        <div class="col-xl-3 py-md-3 mx-md-3 border border-dark text-center" style="background-color:#ffffff; width: 300px; height: 100px;">
          <%= link_to new_card_path(id: @payment_id) do %>
          <%= image_tag("add_icon.png",size: "60") %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container-fluid">

  <div class="row">

    <div class="col-xl-2" style="background-color:#ffffff">

      <%= render partial: "layouts/side_navbar",locals: {selected: "cart"}%>
    </div>

    <div class="col-xl-9" style="width: 1000px; background-color:#4B515D">

      <div class="px-xl-5 py-xl-5">
        <%= form_for :card, url: cards_path(id: @payment_id,type: "order"), method: "post", html: {class: "form-horizontal center text-light"} do |f| %>

        <div class="row">

          <div class="col-xl-6">

            <div class="row pl-xl-3">
              <%= f.label "Card Number:",class: " control-label" %>
            </div>
            <%= f.text_field :card_number, class: "form-control" %>

            <% if @card.errors[:card_number].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @card.errors[:card_number].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>

          <div class="col-xl-6">

            <div class="row pl-xl-3">
              <%= f.label "Expiry:", class: " control-label" %>
            </div>
            <%= f.date_field :expiry,class: "form-control" %>
            <%= f.hidden_field :user_id,value: current_user.id,class: "form-control" %>

            <% if @card.errors[:expiry].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @card.errors[:expiry].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>
        </div>

        <div class="row">

          <div class="col-xl-6">

            <div class="row pl-xl-3 py-xl-2">
              <%= f.label "CVV:", class: " control-label" %>
            </div>
            <%= f.text_field :cvv, class: "form-control" %>

            <% if @card.errors[:cvv].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @card.errors[:cvv].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>

          <div class="col-xl-6">

            <div class="row pl-xl-3 py-xl-2">
              <%= f.label "Card Holer Name:", class: " control-label" %>
            </div>
            <%= f.text_field :card_holder_name, class: "form-control" %>

            <% if @card.errors[:card_holder_name].any?%>
            <div class="row pl-xl-3 text-left">
              <div class="text-danger">
                <% @card.errors[:card_holder_name].each do |error| %>
                  **<%= error %> <br>
                <% end %>
              </div>
            </div>
            <% end %>

          </div>

        </div>


        <div class="row pt-xl-5 pl-xl-3">
          <%= f.submit "Add Card", class: "btn btn-default btn-primary" %>
        </div>
        <% end %>

      </div>
    </div>
  </div>

</div>